language: node_js
sudo: required
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '10'
install:
- npm ci
script:
- npm run travis:verify
after_success:
- bash .travis/after_success.sh
env:
  global:
  - REPO="git@github.com:juiceboxes/juiceboxes.github.io"